<?php $form = $this->form; ?>
 <div class="boxBorderBottom">
   <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
     <tr>
        <td valign="middle"><h2 class="filterIcon">Add Home Wallpaper</h2></td>
     </tr>
   </table>
</div>
<div id="filterBox">
<?php 
  //echo $this->duplicate
?>
  
  <form id="formwallpaperadd" name="formwallpaperadd" method="<?php echo $form->getMethod(); ?>" action="<?php echo $form->getAction(); ?>" enctype="multipart/form-data" onsubmit="return false;">
	<table>
		<tr>
			<td align="center" colspan="2">&nbsp;</td>
		</tr>
 		<tr>
	    	<td><?php echo $form->order->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->order->renderViewHelper() ?>
	        	<?php echo $form->order->renderErrors()?>  
			</td>
		</tr>
 	    <tr>
	    	<td><?php echo $form->status->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->status->renderViewHelper() ?> 
			</td>
		</tr>
 	      <tr>
	    	<td>Image (Ipad)</td>
	        <td>
	        	 <?php echo $form->image_ipad ?> 
	        	 <input type="hidden" id='ipad_logo'>
	        </td>
		</tr>
 		<tr>
	    	<td>Image (Ipad3)</td>
	        <td>	
	        	<?php echo $form->image_ipad_3 ?>
	        	<input type="hidden" id='ipad3_logo'> 
			</td>
		</tr>
		<tr>
	    	<td>Image (Iphone)</td>
	        <td>
	        	<?php echo $form->image_iphone ?>
	        	<input type="hidden" id='iphone_logo'> 
			</td>
		</tr>
		<tr>
	    	<td>Image (Android)</td>
	        <td>
	        	<?php echo $form->image_android ?>
	        	<input type="hidden" id='android_logo'> 
			</td>
		</tr>
		<tr>
	    	<td><?php echo $form->link_to_module->renderLabel() ?></td>
	        <td>
	        	<?php echo $form->link_to_module->renderViewHelper() ?> 
	        </td>
		</tr>
	 	<tr> 
	    	<td>&nbsp;</td>
	        <td>&nbsp;</td>
		</tr>
		<tr>
			<td align="center" colspan="2">
				<?php echo $form->submit->renderViewHelper() ?>&nbsp;
				<?php echo $form->reset->renderViewHelper() ?>&nbsp;
				<?php echo $form->cancel->renderViewHelper() ?>
			</td>
		</tr>
	</table>
  </form>
</div> 
<script type="text/javascript"> 
 
$(document).ready(function() { 
	$("#formwallpaperadd").validator();  
	
	$("#formwallpaperadd").submit(function(){
		
		if(!$("#formwallpaperadd").data("validator").checkValidity()) return false;
		
		var form = $(this);	 
           $(document).queue(function(next){
        	   prompt = new prompt({
	  					reference: form,
	  					element: '#content',	
	  					beforeShow : function(){
			                this.alternateMessage = this.showLoadingMessage("Saving Wallpaper Details...");
		                }	
					});
					next();
           }).queue(function(next){
        	   $.ajaxFileUpload({ 
        		    url: '<?php echo $form->getAction(); ?>',
					secureuri: false,
					fileElementId: 'image_ipad',
					dataType: 'json',
					data:{upload:'true'}, 
      				success: function (data){  
          				console.log(data.success_ipad);
          				if(data.success_ipad != undefined) {
							$("#ipad_logo").attr("value",data.success_ipad); 
							next();
						}
      				},
      				error: function (data){
						promptus.showErrorMessage(data.error_ipad);
						setTimeout(function(){
							promptus.close();
						}, 2000);
						
					}
      			});
        	   next();
           }).queue(function(next){
        	   $.ajaxFileUpload({ 
          		    url: '<?php echo $form->getAction(); ?>',
   					secureuri: false,
   					fileElementId: 'image_ipad_3',
   					dataType: 'json',
   					data:{upload:'true'}, 
        			success: function (data, status){  
            			if(data.success_ipad3 != undefined) {
   							$("#ipad3_logo").attr("value",data.success_ipad3); 
   							next();
   						}
        			},
        			error: function (data, status){
   						promptus.showErrorMessage(data.error_ipad3);
   						setTimeout(function(){
   							promptus.close();
   						}, 2000);
   						
   					}
        	   });
          	  next(); 
           }).queue(function(next){
        	   $.ajaxFileUpload({ 
          		    url: '<?php echo $form->getAction(); ?>',
   					secureuri: false,
   					fileElementId: 'image_iphone',
   					dataType: 'json',
   					data:{upload:'true'}, 
        			success: function (data, status){  
            			if(data.success_iphone != undefined) {
   							$("#iphone_logo").attr("value",data_iphone.success); 
   							next();
   						}
        			},
        			error: function (data, status, e){
   						promptus.showErrorMessage(data.error_iphone);
   						setTimeout(function(){
   							promptus.close();
   						}, 2000);
   						
   					}
        	   });
          	  next(); 
           }).queue(function(next){
        	   $.ajaxFileUpload({ 
          		    url: '<?php echo $form->getAction(); ?>',
   					secureuri: false,
   					fileElementId: 'image_android',
   					dataType: 'json',
   					data:{upload:'true'}, 
        			success: function (data, status){  
            			if(data.success_android != undefined) {
   							$("#android_logo").attr("value",data_android.success); 
   							next();
   						}
        			},
        			error: function (data, status, e){
   						promptus.showErrorMessage(data.error_android);
   						setTimeout(function(){
   							promptus.close();
   						}, 2000);
   						
   					}
        	   });
          	  next(); 
		   }).queue(function(next){ 
			    var formData = form.serialize();
				$.ajax({
					url: "<?php echo $form->getAction(); ?>",
					type:"POST",
					dataType:"json",
					data:formData,
					success:function(reponse){	 
						if(!reponse.error){
							prompt.showSuccessMessage("wallpaper saved successfully.");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"wallpaper","controller"=>"index","action"=>"index"),null,true); ?>";
							}, 2000); 
						}
					}
				});
		  }).queue(function(next){
				prompt.close();
				next();	
		  });
	});
	
});
 	 
</script>
 