<div class="boxBorderBottom">
   <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
     <tr>
        <td valign="middle"><h2 class="filterIcon">&nbsp;Home Wallpaper</h2></td>
     </tr>
   </table>
</div>
<table style="border-spacing: 0; border-collapse: collapse; width: 100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Status</th>
			<th scope="col">Order</th>
 			<th scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="2" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	// Load Grid Data
	grid = dataTable({
		aaSorting: [[ 0, "desc" ]],
		aoColumns: [
	              	{ "sName": "wallpaper_id"},
					{ "sName": "status" },
					{ "sName": "order" },					
 					{ "sName": "actions","bSortable": false}
				   ],
		id : $('#dataGrid'), 
		sAjaxSource: "<?php echo $this->url(array("module"=>"wallpaper","controller"=>"index","action"=>"grid"),"default",true);?>"
	});
	
    

    $(document).on("click",".grid_delete",function(e){
        var self = this; 
        
		window.currentBusinessTypeDeleteUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented())
        {
        	var promtus = new prompt({
            	reference : self,
                element : ".dataTables_wrapper",
                message : "Are you sure you want to delete this wallpaper ?",
                buttons : {
                    "Yes" : function(self){
                        var prompt = this;
                        $(document).queue(function(next){
                            prompt.showLoadingMessage("Please wait while deleting wallpaper..");
                            next();
                        }).queue(function(next){
                        	$.ajax({
                                url: window.currentBusinessTypeDeleteUrl,
                                cache: false,
                                type: "GET",
                                dataType: "json",
                                success: function(json){
                                    if(json.success != undefined)
                                    { 
                                    	prompt.showSuccessMessage("Wallpaper deleted successfully.");
                                    	setTimeout(function(){
                                    		prompt.close();
                                        	grid.fnDraw();
                                        }, 1000);
                                    } 
                                    else if(json.errors != undefined)
                                    {
                                        var errorMessage = "Unable to delete record error returned:<br />";
                                        errorMessage += json.errors.message;
                                    	prompt.showErrorMessage(errorMessage);
                                    	setTimeout(function(){
                                    		prompt.close();
                                        }, 2000);
                                    }
                                },
                                error: function(){
                                }
                            }).complete(next); 
                        });
                    },
                    "No"  : function(self){
                    	this.close();
                    },
                }
            });
            e.preventDefault();
        }
    });
});
</script>