<?php 
$data = $this->data;
$image_dir = Standard_Functions::getResourcePath () . "home-wallpaper/wallpapers/C" . Standard_Functions::getCurrentUser ()->customer_id . "/";
$image_uri = $this->baseUrl("resource/home-wallpaper/wallpapers/C" . Standard_Functions::getCurrentUser ()->customer_id . "/");
?>
<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon"><?php echo $this->translate('Reorder Home Wallpaper'); ?></h2></td>
          <td align="right">
          	<input type="submit" name="button" id="save-order" class="button" value="<?php echo $this->translate('Save')?>" />
          	<input type="reset" name="reset" id="reset" class="button" value="<?php echo $this->translate('Reset')?>" />
          </td>
        </tr>
      </table>
</div>
</form>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
			<th scope="col"><?php echo $this->translate('Image Thumbnail view'); ?></th>
		    <th scope="col"><?php echo $this->translate('Image Name'); ?></th>
		    <th scope="col"><?php echo $this->translate('Status'); ?></th>
		</tr>
    </thead> 
	<tbody>
		<?php 
			foreach($data as $row) {
		?>
			<tr id="index-<?php echo $row["h.home_wallpaper_id"];?>" class="sortable" style="cursor: move;">
				<td>
				<?php 
					$image_path = "";
					$ext_ipad = array_pop ( explode ( ".", $row ["image_ipad"] ) );
					$ext_iphone = array_pop ( explode ( ".", $row ["image_iphone"] ) );
					$ext_ipad_3 = array_pop ( explode ( ".", $row ["image_ipad_3"] ) );
					$ext_android = array_pop ( explode ( ".", $row ["image_android"] ) );
					$ext_ios_6 = array_pop ( explode ( ".", $row ["image_ios_6"] ) );
					if ($row ["image_ipad"]!="" && file_exists ( $image_dir . str_replace ( "." . $ext_ipad, "_thumb." . $ext_ipad, $row ["image_ipad"] ) )) {
						$image_path = str_replace ( "." . $ext_ipad, "_thumb." . $ext_ipad, $row ["image_ipad"] );
					} else if ($row ["image_iphone"] && file_exists ( $image_dir . str_replace ( "." . $ext_iphone, "_thumb." . $ext_iphone, $row ["image_iphone"] ) )) {
						$image_path = str_replace ( "." . $ext_iphone, "_thumb." . $ext_iphone, $row ["image_iphone"] );
					} else if ($row ["image_ipad_3"]  && file_exists ( $image_dir . str_replace ( "." . $ext_ipad_3, "_thumb." . $ext_ipad_3, $row ["image_ipad_3"] ) )) {
						$image_path = str_replace ( "." . $ext_ipad_3, "_thumb." . $ext_ipad_3, $row ["image_ipad_3"] );
					} else if ($row ["image_android"] && file_exists ( $image_dir . str_replace ( "." . $ext_android, "_thumb." . $ext_android, $row ["image_android"] ) )) {
						$image_path = str_replace ( "." . $ext_android, "_thumb." . $ext_android, $row ["image_android"] );
					} else if ($row ["image_ios_6"] && file_exists ( $image_dir . str_replace ( "." . $ext_android, "_thumb." . $ext_android, $row ["image_ios_6"] ) )) {
						$image_path = str_replace ( "." . $ext_android, "_thumb." . $ext_android, $row ["image_ios_6"] );
					}
					if ($image_path != "") {
						echo "<img src='" . $image_uri . $image_path . "' title='" . $row ["hd.image_title"] . "' />";
					} else {
						echo "No Image Found";
					}
				?>
				</td>
			    <td><?php echo $row['hd.image_title']; ?></td>
			    <td><?php echo ($row['h.status']==1)? "Active" : "Inactive"; ?></td>
			</tr>
		<?php } ?>
	</tbody>      
</table>

<script type="text/javascript">
$(document).ready(function() {
	window.dragStartIndex = 0;
	//  $(".sortable:eq(1)").insertBefore($(".sortable:eq(0)"));
	$(".sortable").on("mousedown",function(){
		window.dragStartIndex = $(this).index(".sortable") + 1;
	});
	$(".sortable").on("mouseup",function(){
		if(window.dragStartIndex>0 && window.dragStartIndex != ($(this).index(".sortable") + 1)) {
			var fromIndex = window.dragStartIndex - 1;
			var toIndex = $(this).index(".sortable");
			if(fromIndex > toIndex) {
				$(".sortable:eq("+fromIndex+")").insertBefore($(".sortable:eq("+toIndex+")"));
			} else {
				$(".sortable:eq("+fromIndex+")").insertAfter($(".sortable:eq("+toIndex+")"));
			}
		}
	});
	$(window).on("mouseup",function(){window.dragStartIndex = 0;});
	$(window).on("mousedown",function(){return false;});

	$(document).on("click","#save-order",function(e){
        var self = this;
        window.currentDeleteUrl = location.href; 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : "#content",
                        message : "<?php echo $this->translate('Are you sure you want to save home wallpaper order?'); ?>",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("<?php echo $this->translate('Please wait while saving home wallpaper order..'); ?>");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "POST",
                                        dataType: "json",
                                        data: serializeOrder(),
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("<?php echo $this->translate('Home wallpaper reordered successfully.'); ?>");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "<?php echo $this->translate('Unable to reorder home wallpaper:'); ?><br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
    
	$("#reset").on("click", function(){
		location.href = location.href;
	});
});
function serializeOrder(){
	var response = {order:{}};
	$(".sortable").each(function(){
		var index = ($(this).attr("id") + "").replace("index-","");
		response["order"][$(this).index(".sortable")+1] = index;
	});
	return response;
}
document.onselectstart = function() {return false;}
</script>