<?php $form = $this->form; ?>
<script type="text/javascript" src="<?php echo $this->baseUrl("libs/tinymce/js/tiny_mce.js"); ?>"></script>
<script type="text/javascript">
tinyMCE.init({
	// General options
	mode : "textareas",
	theme : "advanced",
	//plugins : "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,visualblocks",
	plugins : "paste,pagebreak,table",
	// set value of textarea if null
	onchange_callback : "textAreaValueChange",
	// Theme options
	theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,undo,redo,|,bullist,numlist,|,outdent,indent,blockquote,|,forecolor,backcolor,|,tablecontrols,|,hr",
	//theme_advanced_buttons1 : "formatselect,fontselect,fontsizeselect,|,forecolor,backcolor,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,code",
	theme_advanced_buttons2 : "",
	//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,ltr,rtl",
	//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,pagebreak",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : true,

	// Example content CSS (should be your site CSS)
	content_css : "<?php echo $this->baseUrl("libs/tinymce/css/content.css"); ?>",

	// Drop lists for link/image/media/template dialogs
	template_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/template_list.js"); ?>",
	external_link_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/link_list.js"); ?>",
	external_image_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/image_list.js"); ?>",
	media_external_list_url : "<?php echo $this->baseUrl("libs/tinymce/js/lists/media_list.js"); ?>",

	// Style formats
	style_formats : [
		{title : 'Bold text', inline : 'b'},
		{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
		{title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
		{title : 'Example 1', inline : 'span', classes : 'example1'},
		{title : 'Example 2', inline : 'span', classes : 'example2'},
		{title : 'Table styles'},
		{title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
	],
	// Replace values for the template plugin
	template_replace_values : {
		username : "Some User",
		staffid : "991234"
	}
});
function textAreaValueChange(inst){
	description.value = tinyMCE.get('description').getContent();
}
</script>

<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
          <td align="right"><h2><?php echo $this->language; ?></h2></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditPushMessage" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php  echo $form->push_message_id->renderViewHelper();?>
	<?php  echo $form->language_id->renderViewHelper();?>
	<?php  echo $form->push_message_detail_id->renderViewHelper();?>
	
	<table style="margin:10px 0;">
		<tbody>
			
			<tr>
		    	<td><?php echo $form->title->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->title->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->description->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->description->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->status->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->status->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td></td>
		        <td>
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#frmAddEditPushMessage").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#frmAddEditPushMessage",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("<?php echo $this->translate('Saving Message..')?>");
	                }
	            });
	            next();
			}).queue(function(next){
				jQuery.ajax({
					url: "<?php echo $this->url(array("module"=>"push-message","controller"=>"index","action"=>"save"),null,true); ?>",
					type:"POST",
					dataType:"json",
					data:form.serialize(),
					success:function(data){
						if(!data.error)
						{
							promptus.showSuccessMessage("<?php echo $this->translate('Message saved successfully.')?>");
			            	setTimeout(function(){
			            		promptus.close();
			            		location.href = "<?php echo $this->url(array("module"=>"push-message","controller"=>"index","action"=>"index"),"default",true); ?>";
			            		next();
			                }, 2000);
						} else {
							promptus.showErrorMessage(data.message);
							setTimeout(function(){
								promptus.close();
								next();
			                }, 2000);
						}
					},
					error: function(){
						promptus.showErrorMessage("<?php echo $this->translate('Error occured') ?>");
						setTimeout(function(){
							promptus.close();
							next();
			            }, 2000);
					}
				});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
// -->
</script>