<?php $form = $this->form; ?>
<style>
	#gMap{
        margin: auto;
        border: 1px solid #DCDDE2;
        width: 100%;
        height: 400px;
    }
</style>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditContact" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->contact_id->renderViewHelper()?>
	<table style="margin:10px 0; width:100%;">
		<tbody>
			<tr>
		    	<td><?php echo $form->location->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->location->renderViewHelper()?>
				</td>
				<td rowspan="13" valign="top" align="center" style="padding-bottom: 0 !important;padding-top: 0 !important;">
					<table cellspacing="0" cellpadding="0" style="width:100%;">
						<tr>
					    	<td><?php echo $form->latitude->renderLabel() ?></td>
					        <td>
					        	<?php echo $form->latitude->renderViewHelper()?>
							</td>
					    	<td><?php echo $form->longitude->renderLabel() ?></td>
					        <td>
					        	<?php echo $form->longitude->renderViewHelper()?>
							</td>
							<td>
								<input type="checkbox" checked="checked" name="mark-fixed" id="mark-fixed" />
								<label for="mark-fixed">Auto Locate</label>
							</td>
						</tr>
						<tr>
							<td colspan="5">
								<div id="gMap"></div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->address->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->address->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone_1->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone_1->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone_2->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone_2->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone_3->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone_3->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->fax->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->fax->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email_1->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email_1->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email_2->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email_2->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email_3->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email_3->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->website->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->website->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->timings->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->timings->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><label for="logo">Logo</label> </td>
		        <td>
		        	<input id="logo" type="file" name="logo" />
		        	<input id="logo_path" type="hidden" name="logo_path" />
				</td>
			</tr>
			<tr>
		    	<td></td>
		        <td>
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
// <!--
$(document).ready(function() {
	$("#frmAddEditContact").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Contact...");
	                }
	            });
	            next();
			}).queue(function(next){
				if($('#logo_path').attr("value")!="") {
					$.ajaxFileUpload({
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'logo',
						dataType: 'json',
						data:{upload:'true'},
						success: function (data, status)
						{
							console.log(data);
							console.log(typeof(data.success));
							if(data.success != undefined) {
								$("#logo_path").attr("value",data.success);
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("Error uploading logo.");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					});
				} else {
					next();
				}
			}).queue(function(next){
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("Contact saved successfully.");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"contact","controller"=>"index","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});

	// Initialize Google Map
	$('#gMap').gmap3({
    	action: 'init',
        options:{
        	center:[0, 0],
        	zoom: 1
        },
        callback: function(){
            
        }
    });

    // Set current geo-loaction on Map
    if($("#latitude").attr("value")=="" && $("#longitude").attr("value")=="")
    {
    	var url = "http://www.geoplugin.net/json.gp?jsoncallback=?";

    	$(document).queue(function(next){

    		if(navigator.geolocation) {
        		var locationMarker = null;
        		navigator.geolocation.getCurrentPosition(function(position) {
            		if(locationMarker) {
    					return;
            		}
            		$('#gMap').gmap3('setDefault', {init:{center:[ position.coords.latitude,position.coords.longitude ]}});
               		$("#latitude").attr("value",position.coords.latitude);
           			$("#longitude").attr("value",position.coords.longitude);

           			next();
        		}, function() {
        			
        		});
        	} 
        	
        	if($("#latitude").attr("value")=="" && $("#longitude").attr("value")=="") {    		
        		$.getJSON(url, function(data){
                	if(data['geoplugin_status'] == 200){
            	        // Do something with the data
            	    	$('#gMap').gmap3('setDefault', {init:{center:[ data["geoplugin_latitude"],data["geoplugin_longitude"] ]}});
        				//$('#gMap').gmap3({action: 'setCenter', args:[ data["geoplugin_latitude"],data["geoplugin_longitude"] ]});
                   		$("#latitude").attr("value",data["geoplugin_latitude"]);
               			$("#longitude").attr("value",data["geoplugin_longitude"]);
            	    }
            	    else
            	    {
            	    	$('#gMap').gmap3('setDefault', {init:{center:[ 0,0 ]}});
                   		$("#latitude").attr("value",0);
               			$("#longitude").attr("value",0);
            	    }
            	}).complete(next);
        	}
    	}).queue(function(next){
    		// Set Marker to the current geo-location
           	$('#gMap').gmap3({ 
                action: 'addMarker',
                latLng:[$("#latitude").attr("value"),$("#longitude").attr("value")],
    			options:{
                	draggable: true,
                    animation: google.maps.Animation.DROP
                },
                events:{
                	drag: function(marker, event, data) {
                		var pos = marker.getPosition();
                    	$("#latitude").attr("value",pos.lat());
                    	$("#longitude").attr("value",pos.lng());
                	}
                }
            });
			next();
    	});    	
    } else {
    	// Set Marker to the current geo-location
    	$("#mark-fixed").removeAttr("checked");
       	$('#gMap').gmap3({ 
            action: 'addMarker',
            latLng:[$("#latitude").attr("value"),$("#longitude").attr("value")],
			options:{
            	draggable: true,
                animation: google.maps.Animation.DROP
            },
            events:{
            	drag: function(marker, event, data) {
            		var pos = marker.getPosition();
                	$("#latitude").attr("value",pos.lat());
                	$("#longitude").attr("value",pos.lng());
            	}
            }
        });
    }
    // Callback to auto set marker based on address
    $("#address").on("blur",function(){
    	if($("#mark-fixed").attr("checked")!="checked") return;
        $('#gMap').gmap3({
    		action:'getAddress',
    		address:$("#address").attr("value"),
    		callback:function(results){
    			if (!results) return;
    			var item = results[0];
    			$("#gMap").gmap3(
    	    		{action:'clear', name:'marker'},
    				{
        				action:'addMarker',
    					latLng:item.geometry.location,
    					options:{
  				        	draggable: true,
  				            animation: google.maps.Animation.DROP
  				        },
  				        events:{
  				        	drag: function(marker, event, data) {
  				        		var pos = marker.getPosition();
  				            	$("#latitude").attr("value",pos.lat());
  				            	$("#longitude").attr("value",pos.lng());
  				        	}
  				        }
    				}
        		);
    			var pos = item.geometry.location;
            	$("#latitude").attr("value",pos.lat());
            	$("#longitude").attr("value",pos.lng());
    		}
    	});
	});
	
    // Callback to auto set marker based on latitude and longitude
    $("#latitude,#longitude").on("blur",function(){
    	if($("#mark-fixed").attr("checked")!="checked") return;
        $("#gMap").gmap3(
			{action:'clear', name:'marker'},
			{
    			action:'addMarker',
				latLng:[$("#latitude").attr("value"),$("#longitude").attr("value")],
				options:{
					draggable: true,
				    animation: google.maps.Animation.DROP
				},
				events:{
					drag: function(marker, event, data) {
				    	var pos = marker.getPosition();
				        $("#latitude").attr("value",pos.lat());
				        $("#longitude").attr("value",pos.lng());
					}
				}
			}
		);
	});
});
// -->
</script>