<?php $form = $this->form; ?>
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><?php echo $this->partial($this->partial,array()); ?></td>
        </tr>
      </table>
</div>
<div class="boxBorderBottom">
<form id="frmAddEditContact" method="<?php echo $form->getMethod();?>" action="<?php echo $form->getAction();?>" class="zend_form">
	<?php echo $form->contact_id->renderViewHelper()?>
	<table style="margin:10px 0;">
		<tbody>
			<tr>
		    	<td><?php echo $form->location->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->location->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->address->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->address->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone_1->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone_1->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone_2->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone_2->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->phone_3->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->phone_3->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->fax->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->fax->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->latitude->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->latitude->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->longitude->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->longitude->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email_1->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email_1->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email_2->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email_2->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->email_3->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->email_3->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->website->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->website->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><?php echo $form->timings->renderLabel() ?></td>
		        <td>
		        	<?php echo $form->timings->renderViewHelper()?>
				</td>
			</tr>
			<tr>
		    	<td><label for="logo">Logo</label> </td>
		        <td>
		        	<input id="logo" type="file" name="logo" />
		        	<input id="logo_path" type="hidden" name="logo_path" />
				</td>
			</tr>
			<tr>
		    	<td></td>
		        <td>
		        	<?php echo $form->submit->renderViewHelper() ?>&nbsp;
					<?php echo $form->reset->renderViewHelper() ?>
				</td>
			</tr>
		</tbody>
	</table>
</form>
</div>
<script type="text/javascript">
<!--
$(document).ready(function() {
	$("#frmAddEditContact").validator().submit(function(e){
		var form = $(this);
		if(!e.isDefaultPrevented()){
			var promptus = false;
			$(document).queue(function(next){
				promptus = new prompt({
	            	reference : form,
	                element : "#content",
	                beforeShow : function(){
		                this.alternateMessage = this.showLoadingMessage("Saving Contact...");
	                }
	            });
	            next();
			}).queue(function(next){
				$.ajaxFileUpload(
					{
						url:'<?php echo $form->getAction(); ?>',
						secureuri:false,
						fileElementId:'logo',
						dataType: 'json',
						data:{upload:'true'},
						success: function (data, status)
						{
							console.log(data);
							console.log(typeof(data.success));
							if(data.success != undefined) {
								$("#logo_path").attr("value",data.success);
								alert("Before Executing Next()");
								next();
							}
						},
						error: function (data, status, e)
						{
							promptus.showErrorMessage("Error uploading logo.");
							setTimeout(function(){
								promptus.close();
							}, 2000);
							
						}
					}
				);
			}).queue(function(next){
				alert("Executing Next()");
				$.ajax({
					type : "POST",
					cache : false,
					data : form.serialize(),
					url : "<?php echo $form->getAction(); ?>",
					success : function(json){
						if(json["errors"] != undefined){
							form.data("validator").invalidate(json["errors"]);
							next();
						} else if(json["success"] != undefined){
							promptus.showSuccessMessage("Contact saved successfully.");
							setTimeout(function(){
								location.href = "<?php echo $this->url(array("module"=>"contact","controller"=>"index","action" => "index"),"default",true);?>";
							}, 2000);
						}
					},
					error : next
	  			});
			}).queue(function(next){
				promptus.close();
				next();
	  		});
			e.preventDefault();
		}
	});
});
-->
</script>