<?php
$form = $this->form;
// Remove <dt> from label generation
foreach ($form->getElements() as $element) {
    if($element->getDecorator('Label')) $element->getDecorator('Label')->setTag(null);
}
?>
<form class="box login" method="<?php echo $form->getMethod() ?>" action="<?php echo
    $form->getAction()?>">
    <fieldset class="boxBody">
	<?php
		if(isset($this->loginMessage))
		{
		?>
		<label class="errors"><?php echo $this->loginMessage; ?></label>
		<?php 
		}
	?>
	<?php echo $form->email->renderLabel() ?>
	  <?php echo str_replace('"text"' , '"email"',$form->email->renderViewHelper()); ?>
	  <?php echo $form->password->renderLabel() ?><label class="forgot"><a href="<?php echo $this->url(array("module"=>"admin","controller"=>"login","action"=>"forgot"))?>" class="rLink" tabindex="5">Forget your password?</a></label>
	  <?php echo $form->password->renderViewHelper() ?>
	</fieldset>
	<footer>
	  <?php echo $form->remember->renderViewHelper()." ";?><?php echo $form->remember->renderLabel(); ?>
	  <?php echo $form->submit->renderViewHelper() ?>
	</footer>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$("#password").attr("value","<?php echo $this->password; ?>");
	$("form").validator();
});
</script>