<form id="frmFilter">
	<div id="filterBox">
		<table
			style="width: 100%; border: 0; border-spacing: 0; border-collapse: collapse;">
			<tr>
				<td valign="middle"><h2 class="filterIcon">Filter</h2></td>
				<td>
					<table>
						<tr>
							<td>Business Type</td>
							<td><input type="text" name="name" class="input" id="txtEmail"></td>
						</tr>
					</table>
				</td>
				<td>&nbsp;</td>
				<td align="right"><input type="submit" name="button" id="button"
					class="button" value="Submit"></td>
			</tr>
		</table>
	</div>
</form>
<table style="border-spacing: 0; border-collapse: collapse; width: 100%"
	class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
			<th scope="col">Business Type ID</th>
			<th scope="col">Business Type</th>
			<th scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="2" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	// Load Grid Data
	grid = dataTable({
		aaSorting: [[ 0, "desc" ]],
		aoColumns: [
	              	{ "sName": "business_type_id"},
					{ "sName": "name" },
					{ "sName": "actions","bSortable": false}
				 ],
		id : $('#dataGrid'),
		filterForm : $('#frmFilter'),
		sAjaxSource: "<?php echo $this->url(array("module"=>"admin","controller"=>"business-type","action"=>"grid"),"default",true);?>"
	});
    $(document).on("submit","#frmFilter",function(){
    	grid.fnDraw();
    	return false;
    });

    $(document).on("click",".grid_delete",function(e){
        window.currentBusinessTypeDeleteUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented()){
        	var promtus = new prompt({
                element : ".dataTables_wrapper",
                message : "Are you sure you want to delete this Business Type?",
                buttons : {
                    "Yes" : function(){
                        alert("Yes Clicked");
                        console.log(this);
                        return false;
                    },
                    "No"  : function(){
                        alert("No Clicked");
                    	console.log(this);
                    	return false;
                    }
                }
            });
            var message = '<div class="confirm_wrapper">';
            message += '	Are you sure you want to delete this Business Type?<br />';
            message += '	<div class="confirm">';
            message += '		<button class="button" value="yes">Yes</button>';
            message += '		<button class="button" value="no">No</button>';
            message += '	</div>';
            message += '</div>';
            /*$(".dataTables_wrapper").block({
                message : message
            });
            */
            e.preventDefault();
        }
    });
    $(document).on("click","div.confirm button.button",function(e){
        if(!e.isDefaultPrevented()){
            if($(this).attr("value")=="no"){
            	$(".dataTables_wrapper").unblock();
            	window.currentBusinessTypeDeleteUrl = undefined;
            } else {
            	$(".confirm_wrapper").html("Deleting Business Type..");
                $.ajax({
                    url: window.currentBusinessTypeDeleteUrl,
                    cache: false,
                    type: "GET",
                    dataType: "json",
                    success: function(json){
                        if(json.success != undefined){
                            var successMessage = '<div class="grid_success">Business Type deleted successfully.</div>'; 
                        	$(".confirm_wrapper").html(successMessage);
                        	setTimeout(function(){
                        		$(".dataTables_wrapper").unblock();
                            	grid.fnDraw();
                            }, 1000);
                        } else if(json.errors != undefined){
                        	var errorMessage = '<div class="grid_error">';
                        	errorMessage += "Unable to delete record error returned: <br />";
                        	errorMessage += "<strong>"+ json.errors.message +"</strong>";
                        	errorMessage += "</div>";
                        	$(".confirm_wrapper").html(errorMessage);
                        	setTimeout(function(){
                        		$(".dataTables_wrapper").unblock();
                            }, 2000);
                        }
                    },
                    error: function(){
                    }
                })
            }
        }
    });
});
function prompt(params){
	this.element = params.element != undefined ? $(params.element) : $(document);
	this.message = params.message || "Are you sure?";
	this.buttons = params.buttons || {
			"Yes" : function(){
				this.close();
			},
			"No"  : function(){
				this.close();
			}
		};
	this.close = function(){
		alert("closing..");
		this.element.unblock();
	};

	this.createMessage = function(){
		
		var message = '<div class="confirm_wrapper">';
        message += this.message;
        message += '	<br />';
        message += '	<div class="confirm">';
        message += '	</div>';
        message += '</div>';
        message = $(message);
        $.each(this.buttons , function(buttonName, associatedFunction){
            var button = $("<button></button>",{
                'class' : "button",
                'value' : buttonName
            });
            button.html(buttonName);
            $(message).find(".confirm").append(button);
        });
		return message.html();
	};

	this.bindEvents = function(){
		$.each(this.buttons,function(buttonName,associatedFunction){
			$(this).on("click",$(".confirm > " + "button[value="+ buttonName +"]"),associatedFunction);
		});
	}
	this.init = function(self){
		
		$(document).queue(function(next){
			self.element.block({
				message: self.createMessage(),
				onBlock: next
			});
		}).queue(function(next){
			self.bindEvents();
			next();
		});
		
	}(this);
}
</script>