<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon">Filter</h2></td>
          <td>
          	<table>
              <tr>
                <td>Template Name</td>
                <td><input type="text" name="t_name" class="input" id="txtTemplate" name="template"></td>
                <td>Business Type</td>
                <td><input type="text" name="bt[name]" class="input" id="txtEmail" name="email"></td>
                <td>Status</td>
                <td><input type="text" name="t_status" class="input" id="txtRole" name="role"></td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
          	<input type="submit" name="button" id="button" class="button" value="Submit">
          </td>
        </tr>
      </table>
</div>
</form>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
	        <th scope="col">Template</th>
		    <th scope="col">Business Type</th>
		    <th scope="col">Status</th>
		    <th scope="col">Total Modules</th>
		    <th scope="col">Last Updated</th>
		    <th scope="col">Action</th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="3" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>      
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {

	grid = dataTable({
		aaSorting: [[ 0, "desc" ]],
		"aoColumns": [
						{ "sName": "t_name" },
						{ "sName": "business_type" },
						{ "sName": "t_status" },
						{ "sName": "total_modules" },
						{ "sName": "t_last_updated_at" },
						{ "sName": "actions","bSortable": false}
					 ],
		id : $('#dataGrid'),
		filterForm : $('#frmFilter'),
		sAjaxSource: "<?php echo $this->url(array("module"=>"admin","controller"=>"template","action"=>"grid"));?>"
	});
    $(document).on("submit","#frmFilter",function(){
    	grid.fnDraw();
    	return false;
    });
    
	/*grid = $('#dataGrid').dataTable({    	
    	"aoColumns": [
						{ "sName": "t_name" },
						{ "sName": "business_type" },
						{ "sName": "t_status" },
						{ "sName": "total_modules" },
						{ "sName": "t_last_updated_at" },
						{ "sName": "actions","bSortable": false}
					 ],
		"bPaginate" : true,
		"bDestroy": true,	
        "bProcessing": false,
        "bServerSide": true,
        "bSortClasses": false,       
        "sAjaxSource": "<?php echo $this->url(array("module"=>"admin","controller"=>"template","action"=>"grid"));?>",
        "sServerMethod": "POST",
        	"fnServerParams": function ( aoData ) {
            	tmData= $('#frmFilter').serializeArray();
            	$(tmData).each(function(){
                   	name= $(this).attr("name");
    				value= $(this).attr("value");                
                   	aoData.push( { "name": name, "value": value } );
                });            
            }
    });    
    $("#dataGrid_length,#dataGrid_filter").hide();
    */

    $(document).on("click",".grid_delete",function(e){
        var self = this;
        window.currentDeleteUrl = $(this).attr("href"); 
        if(!e.isDefaultPrevented()){
        	var promptus = new prompt({
                    	reference : self,
                        element : ".dataTables_wrapper",
                        message : "Are you sure you want to delete this Template?",
                        buttons : {
                            "Yes" : function(self){
                                var prompt = this;
                                $(document).queue(function(next){
                                    prompt.showLoadingMessage("Please wait while deleting template..");
                                    next();
                                }).queue(function(next){
                                    $.ajax({
                                        url: window.currentDeleteUrl,
                                        cache: false,
                                        type: "GET",
                                        dataType: "json",
                                        success: function(json){
                                            if(json.success != undefined){ 
                                            	prompt.showSuccessMessage("Template deleted successfully.");
                                            	setTimeout(function(){
                                            		prompt.close();
                                                	grid.fnDraw();
                                                }, 1000);
                                            } else if(json.errors != undefined){
                                                var errorMessage = "Unable to delete template:<br />";
                                                errorMessage += json.errors.message;
                                            	prompt.showErrorMessage(errorMessage);
                                            	setTimeout(function(){
                                            		prompt.close();
                                                }, 2000);
                                            }
                                        },
                                        error: function(){
                                        }
                                    }).complete(next); 
                                });
                            },
                            "No"  : function(self){
                            	this.close();
                            },
                        }
                    });
            e.preventDefault();
        }
    });
});
</script>