<form id="frmFilter" onsubmit="_filter();return false;">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon">Filter</h2></td>
          <td>
          	<table>
              <tr>
                <td>User Email</td>
                <td><input type="text" name="email" class="input" id="txtEmail"></td>
                <td>Role</td>
                <td><input type="text" name="role" class="input" id="txtRole"></td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
          	<input type="submit" name="button" id="button" class="button" value="Submit">
          </td>
        </tr>
      </table>
</div>
</form>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
	        <th scope="col">User Email</th>
		    <th scope="col">Role</th>
		    <th scope="col">Action</th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="3" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>      
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	grid= dataTable({
		id: $('#dataGrid'),
		"aoColumns": [
			{ "sName": "email" },
			{ "sName": "role" },
			{ "sName": "actions","bSortable": false}
		 ],
		 "sAjaxSource": "<?php echo $this->url(array("module"=>"admin","controller"=>"system-user","action"=>"grid"));?>",
		 filterForm : $("#frmFilter")
	});    
    $("#dataGrid_length,#dataGrid_filter").hide();
});
function _filter()
{
	grid.fnDraw();
	return false;	
}
</script>