<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon">Filter</h2></td>
          <td>
          	<table>
              <tr>
                <td>User Email</td>
                <td><input type="text" name="email" class="input" id="txtEmail"></td>
                <td>Role</td>
                <td><input type="text" name="role" class="input" id="txtRole"></td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
          	<input type="submit" name="button" id="button" class="button" value="Submit">
          </td>
        </tr>
      </table>
</div>
