<div id="customer-tabs">
	<ul>
		<li><a href="#customer-information">Customer Information</a></li>
		<li><a href="#customer-configuration">Customer Configuration</a></li>
	</ul>
	<div id="customer-information">
		<p>Customer Information Form</p>
		<?php echo $this->customerForm->render();?>
	</div>
	<div id="customer-configuration">
		<p>Customer Configuration Form</p>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$( "#customer-tabs" ).tabs();
	});
</script>