<form id="frmFilter" onsubmit="_filter();return false;">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon">Filter</h2></td>
          <td>
          	<table>
              <tr>
                <td>Customer Name</td>
                <td><input type="text" name="customer_name" class="input" id="txtCustomerName" /></td>
                <td>Business Type</td>
                <td>
                	<input type="text" name="business_type_id" class="input" id="txtBusinessTypeId" />
                </td>
                <td>Status</td>
                <td>
                	<select name="status">
                		<option value="1">Active</option>
                		<option value="2">InActive</option>
                	</select>
                </td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
          	<input type="submit" name="button" id="button" class="button" value="Submit">
          </td>
        </tr>
      </table>
</div>
</form>
<table width="100%" class="pattern-style-b" cellspacing='0' id="dataGrid">
	<thead>
		<tr>
	        <th scope="col">Customer Name</th>
		    <th scope="col">Business Type</th>
		    <th scope="col">Contact Person</th>
		    <th scope="col">City</th>
		    <th scope="col">Country</th>
		    <th scope="col">Status</th>
		    <th scope="col">Action</th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>      
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	grid = $('#dataGrid').dataTable({    	
    	"aoColumns": [
						{ "sName": "customer_name" },
						{ "sName": "business_type_id" },
						{ "sName": "contact_person_name" },
						{ "sName": "city" },
						{ "sName": "country" },
						{ "sName": "status" },
						{ "sName": "action","bSortable": false}
					 ],
		"bPaginate" : true,
		"bDestroy": true,	
        "bProcessing": false,
        "bServerSide": true,
        "bSortClasses": false,       
        "sAjaxSource": "<?php echo $this->url(array("module"=>"admin","controller"=>"customer","action"=>"grid"));?>",
        "sServerMethod": "POST",
        	"fnServerParams": function ( aoData ) {
            	tmData= $('#frmFilter').serializeArray();
            	$(tmData).each(function(){
                   	name= $(this).attr("name");
    				value= $(this).attr("value");                
                   	aoData.push( { "name": name, "value": value } );
                });            
            }
    });    
    $("#dataGrid_length,#dataGrid_filter").hide();
});
function _filter()
{
	grid.fnDraw();
	return false;	
}
</script>