<form id="frmFilter">
<div id="filterBox">
      <table style="width:100%;border:0;border-spacing:0;border-collapse:collapse;">
        <tr>
          <td valign="middle"><h2 class="filterIcon">Filter</h2></td>
          <td>
          	<table>
              <tr>
                <td>Customer Name</td>
                <td><input type="text" name="customer_name" class="input" id="txtCustomerName" /></td>
                <td>Business Type</td>
                <td>
                	<input type="text" name="bt[name]" class="input" id="txtBusinessTypeId" />
                </td>
                <td>Status</td>
                <td>
                	<select name="c[status]">
                		<option value="1">Active</option>
                		<option value="0">InActive</option>
                	</select>
                </td>
              </tr>
            </table>
          </td>
          <td>&nbsp;</td>
          <td align="right">
          	<input type="submit" name="button" id="button" class="button" value="Submit">
          </td>
        </tr>
      </table>
</div>
</form>
<table style="border-spacing:0;border-collapse:collapse;width:100%" class="pattern-style-b" id="dataGrid">
	<thead>
		<tr>
	        <th scope="col">App Access ID</th>
		    <th scope="col">Business Type</th>
		    <th scope="col">Customer User Name</th>
		    <th scope="col">Customer Name</th>
		    <th scope="col">Contact Person</th>
		    <th scope="col">Status</th>
		    <th scope="col">Action</th>
		</tr>
    </thead> 
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Loading data from server</td>
		</tr>
	</tbody>      
</table>

<script type="text/javascript">
var grid ="";
$(document).ready(function() {
	grid = dataTable({
		aaSorting: [[ 0, "desc" ]],
		"aoColumns": [
						{ "sName": "app_access_id" },
						{ "sName": "bt.name" },
						{ "sName": "u.username" },
						{ "sName": "customer_name" },
						{ "sName": "contact_person_name" },
						{ "sName": "c.status" },
						{ "sName": "actions","bSortable": false}
					 ],
		id : $('#dataGrid'),
		filterForm : $('#frmFilter'),
		sAjaxSource: "<?php echo $this->url(array("module"=>"admin","controller"=>"customer","action"=>"grid"),"default",true);?>",
	});
});
$(document).on("submit","#frmFilter",function(){
	grid.fnDraw();
	return false;
});
</script>